export const figmaAssets = {
  logo: '/figma/logo.png',
  heroInterview: '/figma/hero-interview.webp',
  profileCard: '/figma/profile-card.jpg',
  avatarOne: '/figma/avatar-one.png',
  avatarTwo: '/figma/avatar-two.png',
  avatarThree: '/figma/avatar-three.png',
  avatarFour: '/figma/avatar-four.png',
  teamOffice: '/figma/team-office.webp',
  aboutOfficeTall: '/figma/about-office-tall.webp',
  aboutOfficeSide: '/figma/about-office-side.webp',
  awards: [
    '/figma/award-1.png',
    '/figma/award-2.png',
    '/figma/award-3.png',
    '/figma/award-4.png',
    '/figma/award-5.png',
  ],
  insights: ['/figma/insight-1.webp', '/figma/insight-2.webp', '/figma/insight-3.webp'],
  certificationsBg: '/figma/certifications-bg.jpg',
  certificationsLeftGif: '/figma/certifications-left.gif',
  floatingActions: {
    call: '/figma/floating-call.svg',
    whatsapp: '/figma/floating-whatsapp.svg',
    fileUser: '/figma/floating-file-user.svg',
    file: '/figma/floating-file.svg',
  },
  partners: [
    '/media/image 12.png',
    '/media/image 14.svg',
    '/media/image 16.svg',
    '/media/image 18.svg',
    '/media/image 20.svg',
    '/media/image 22.svg',
    '/media/image 24.svg',
    '/media/image 26.svg',
  ],
  testimonialVideo: '/figma/testimonial-video.png',
} as const
