/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    blogs: Blog;
    services: Service;
    testimonials: Testimonial;
    'team-members': TeamMember;
    faqs: Faq;
    careers: Career;
    'contact-submissions': ContactSubmission;
    'career-applications': CareerApplication;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'career-applications': CareerApplicationsSelect<false> | CareerApplicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | {
        /**
         * Choose the hero composition. Split matches the primary Figma homepage layout.
         */
        variant?: ('split' | 'centered' | 'textOnly' | 'darkSplit') | null;
        /**
         * Small label shown above the main heading.
         */
        eyebrow?: string | null;
        /**
         * Main H1 for the page. Use one clear, keyword-aware headline.
         */
        heading: string;
        /**
         * Optional emphasized phrase displayed with the heading.
         */
        highlight?: string | null;
        /**
         * Concise supporting copy for the hero.
         */
        description?: string | null;
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        primaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        secondaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Controls whether the image collage appears on the left or right. Only used by darkSplit variant.
         */
        imagePosition?: ('right' | 'left') | null;
        /**
         * Primary hero image. Use descriptive alt text on the media item for SEO and accessibility.
         */
        media?: (number | null) | Media;
        /**
         * Small floating label used on the split hero visual.
         */
        badgeLabel?: string | null;
        /**
         * Optional floating profile card used on the split hero visual.
         */
        featureCard?: {
          image?: (number | null) | Media;
          name?: string | null;
          role?: string | null;
          primaryLabel?: string | null;
          primaryValue?: string | null;
          secondaryLabel?: string | null;
          secondaryValue?: string | null;
        };
        /**
         * Optional hero proof points. The first item is highlighted in the visual card.
         */
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Small uppercase label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Main section heading.
         */
        heading: string;
        /**
         * Optional word or phrase within the heading to emphasize with a gradient underline.
         */
        highlight?: string | null;
        /**
         * Optional summary paragraph shown below the heading.
         */
        description?: string | null;
        /**
         * Advantage cards. Each card has an icon, title, and description.
         */
        items?:
          | {
              /**
               * Lucide icon name e.g. Globe, ShieldCheck, Users, Briefcase, Zap, Target.
               */
              icon?: string | null;
              title: string;
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'advantage';
      }
    | {
        /**
         * Strip renders as a compact blue bar. Cards renders as a cream section with icon cards.
         */
        layout?: ('strip' | 'cards') | null;
        /**
         * Section heading shown above the cards. Only used in cards layout.
         */
        heading?: string | null;
        /**
         * Optional description below the heading. Only used in cards layout.
         */
        description?: string | null;
        items: {
          value: string;
          label: string;
          /**
           * Lucide icon name e.g. Globe, Users, Building2, MapPin, Star, ShieldCheck.
           */
          icon?: string | null;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'statsStrip';
      }
    | {
        /**
         * Choose how the media should be composed beside the content.
         */
        layout?: ('overlap' | 'split') | null;
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional word or phrase within the heading to emphasize with a gradient underline.
         */
        highlight?: string | null;
        /**
         * Main body copy. Use short paragraphs and clear subtopics for scannability.
         */
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Primary image. Add descriptive alt text on the media item.
         */
        media: number | Media;
        /**
         * Optional supporting image used by split image sections.
         */
        mediaSecondary?: (number | null) | Media;
        /**
         * Controls whether the image group appears before or after the text on desktop.
         */
        imagePosition?: ('left' | 'right') | null;
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        action?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        primaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        secondaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Optional stats shown as overlay badges on the image in the dark background variant.
         */
        stats?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional profile card displayed on the image in the dark background variant.
         */
        overlayCard?: {
          name?: string | null;
          role?: string | null;
          company?: string | null;
        };
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentImage';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        /**
         * Latest mode is useful for evergreen service landing pages.
         */
        selectionMode?: ('manual' | 'latest') | null;
        /**
         * Select services to feature. Leave empty when using latest mode.
         */
        services?: (number | Service)[] | null;
        columns?: ('2' | '3') | null;
        showIcons?: boolean | null;
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        action?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'servicesGrid';
      }
    | {
        heading: string;
        description?: string | null;
        items?:
          | {
              title: string;
              description: string;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'awards';
      }
    | {
        heading: string;
        items?:
          | {
              label: string;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'certifications';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        primaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        secondaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        items?:
          | {
              label: string;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'industries';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        /**
         * Select testimonials to feature. Leave empty to use featured testimonials.
         */
        items?: (number | Testimonial)[] | null;
        display?: ('featured' | 'grid') | null;
        /**
         * Optional image shown in the featured media grid layout.
         */
        featuredMedia?: (number | null) | Media;
        showRatings?: boolean | null;
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        /**
         * Dark gradient matches the primary contact CTA style from Figma.
         */
        variant?: ('light' | 'darkGradient' | 'bordered') | null;
        alignment?: ('left' | 'center') | null;
        /**
         * Optional supporting image for campaign CTAs.
         */
        media?: (number | null) | Media;
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        primaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        secondaryAction?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        /**
         * Optional category label used by editors to group FAQ sections.
         */
        category?: string | null;
        defaultOpenFirst?: boolean | null;
        /**
         * Select FAQs in the order they should appear. Leave empty to show published FAQs.
         */
        items?: (number | Faq)[] | null;
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        selectionMode?: ('latest' | 'manual') | null;
        /**
         * Select posts manually, or leave empty to show latest published posts.
         */
        posts?: (number | Blog)[] | null;
        /**
         * Maximum number of posts to render.
         */
        limit?: number | null;
        showFeaturedImages?: boolean | null;
        showExcerpts?: boolean | null;
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        action?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogListing';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        selectionMode?: ('manual' | 'latest') | null;
        /**
         * Select team members to feature. Leave empty to show ordered team members.
         */
        members?: (number | TeamMember)[] | null;
        layout?: ('grid' | 'editorial') | null;
        showBio?: boolean | null;
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'team';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        /**
         * Heading shown above the contact form.
         */
        formHeading?: string | null;
        /**
         * Optional helper copy shown inside the form.
         */
        formDescription?: string | null;
        /**
         * Options shown in the "How did you hear about us?" dropdown.
         */
        sourceOptions?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional contact details shown beside the form.
         */
        contactMethods?:
          | {
              label: string;
              value: string;
              /**
               * Optional link, for example tel: or mailto:.
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Internal notification recipients for future email workflows.
         */
        recipients?:
          | {
              email: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        /**
         * Optional short label shown above the heading.
         */
        eyebrow?: string | null;
        /**
         * Primary section heading. Keep it specific and search-friendly.
         */
        heading: string;
        /**
         * Optional summary copy shown near the heading.
         */
        description?: string | null;
        selectionMode?: ('latest' | 'manual') | null;
        /**
         * Select roles manually, or leave empty to show latest published roles.
         */
        careers?: (number | Career)[] | null;
        showFilters?: boolean | null;
        /**
         * Message shown when there are no careers to display.
         */
        emptyState?: string | null;
        /**
         * Optional call-to-action link. Leave blank to hide this button.
         */
        action?: {
          /**
           * Button text shown to visitors.
           */
          label?: string | null;
          /**
           * Use a relative path like /contact, an anchor like #contact, or a full URL.
           */
          url?: string | null;
          newTab?: boolean | null;
        };
        /**
         * Shared controls for editors. These do not change the main content.
         */
        settings?: {
          /**
           * Shown only in Payload to help content teams identify this block.
           */
          adminTitle?: string | null;
          /**
           * Optional URL anchor such as contact or services. Use lowercase letters, numbers, and hyphens.
           */
          anchorId?: string | null;
          background?: ('cream' | 'soft' | 'white' | 'blue' | 'dark') | null;
          spacing?: ('compact' | 'standard' | 'spacious') | null;
          hideBlock?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'career';
      }
  )[];
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  summary: string;
  /**
   * Lucide icon name used by the frontend renderer.
   */
  icon?: string | null;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short bullet points shown on listing rows and service detail pages.
   */
  benefits?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional service delivery steps shown on service detail pages.
   */
  process?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional related services. If left empty, the frontend will show other services.
   */
  relatedServices?: (number | Service)[] | null;
  /**
   * Optional call-to-action link. Leave blank to hide this button.
   */
  cta?: {
    /**
     * Button text shown to visitors.
     */
    label?: string | null;
    /**
     * Use a relative path like /contact, an anchor like #contact, or a full URL.
     */
    url?: string | null;
    newTab?: boolean | null;
  };
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  company: string;
  quote: string;
  rating?: number | null;
  /**
   * Choose video when this testimonial should render with a play overlay.
   */
  testimonialType?: ('text' | 'video') | null;
  /**
   * Optional hosted video URL used by video testimonial cards.
   */
  videoUrl?: string | null;
  avatar?: (number | null) | Media;
  /**
   * Optional thumbnail image for video testimonials. Falls back to the avatar.
   */
  videoThumbnail?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Lower numbers appear earlier on the testimonials page.
   */
  sortOrder?: number | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: string | null;
  order?: number | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt?: string | null;
  featuredImage: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  slug: string;
  role: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  order?: number | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  slug: string;
  department?: string | null;
  location: string;
  employmentType: 'full-time' | 'part-time' | 'contract' | 'internship';
  experience?: string | null;
  summary: string;
  jobDetails?:
    | {
        heading: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  fullName: string;
  email: string;
  company: string;
  phone: string;
  source?: string | null;
  message?: string | null;
  status?: ('new' | 'in-review' | 'responded') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications".
 */
export interface CareerApplication {
  id: number;
  career?: (number | null) | Career;
  fullName: string;
  email: string;
  phone: string;
  currentLocation?: string | null;
  experience?: string | null;
  portfolioUrl?: string | null;
  resume?: (number | null) | Media;
  status?: ('new' | 'shortlisted' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'career-applications';
        value: number | CareerApplication;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              eyebrow?: T;
              heading?: T;
              highlight?: T;
              description?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              secondaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              imagePosition?: T;
              media?: T;
              badgeLabel?: T;
              featureCard?:
                | T
                | {
                    image?: T;
                    name?: T;
                    role?: T;
                    primaryLabel?: T;
                    primaryValue?: T;
                    secondaryLabel?: T;
                    secondaryValue?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        advantage?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              highlight?: T;
              description?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        statsStrip?:
          | T
          | {
              layout?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contentImage?:
          | T
          | {
              layout?: T;
              eyebrow?: T;
              heading?: T;
              highlight?: T;
              body?: T;
              media?: T;
              mediaSecondary?: T;
              imagePosition?: T;
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              primaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              secondaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              overlayCard?:
                | T
                | {
                    name?: T;
                    role?: T;
                    company?: T;
                  };
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              selectionMode?: T;
              services?: T;
              columns?: T;
              showIcons?: T;
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        awards?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        certifications?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        industries?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              secondaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?: T;
              display?: T;
              featuredMedia?: T;
              showRatings?: T;
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              variant?: T;
              alignment?: T;
              media?: T;
              primaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              secondaryAction?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              category?: T;
              defaultOpenFirst?: T;
              items?: T;
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blogListing?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              selectionMode?: T;
              posts?: T;
              limit?: T;
              showFeaturedImages?: T;
              showExcerpts?: T;
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              selectionMode?: T;
              members?: T;
              layout?: T;
              showBio?: T;
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              formHeading?: T;
              formDescription?: T;
              sourceOptions?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              contactMethods?:
                | T
                | {
                    label?: T;
                    value?: T;
                    url?: T;
                    id?: T;
                  };
              recipients?:
                | T
                | {
                    email?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
        career?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              selectionMode?: T;
              careers?: T;
              showFilters?: T;
              emptyState?: T;
              action?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                  };
              settings?:
                | T
                | {
                    adminTitle?: T;
                    anchorId?: T;
                    background?: T;
                    spacing?: T;
                    hideBlock?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  publishedAt?: T;
  featuredImage?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  icon?: T;
  featuredImage?: T;
  content?: T;
  benefits?:
    | T
    | {
        label?: T;
        id?: T;
      };
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  relatedServices?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  quote?: T;
  rating?: T;
  testimonialType?: T;
  videoUrl?: T;
  avatar?: T;
  videoThumbnail?: T;
  featured?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  department?: T;
  location?: T;
  employmentType?: T;
  experience?: T;
  summary?: T;
  jobDetails?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  company?: T;
  phone?: T;
  source?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications_select".
 */
export interface CareerApplicationsSelect<T extends boolean = true> {
  career?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  currentLocation?: T;
  experience?: T;
  portfolioUrl?: T;
  resume?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used as the site name in SEO fallbacks and image alt text.
   */
  brandName: string;
  /**
   * Legacy/shared logo fallback. Prefer the Header and Footer logo fields below.
   */
  logo?: (number | null) | Media;
  header?: {
    /**
     * Logo shown in the website header.
     */
    logo?: (number | null) | Media;
    /**
     * Accessible text for the header logo. Example: INFE Talent.
     */
    logoAlt?: string | null;
    /**
     * Primary navigation shown in the desktop and mobile header.
     */
    navigation?:
      | {
          label: string;
          url: string;
          newTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    cta?: {
      enabled?: boolean | null;
      label?: string | null;
      url?: string | null;
      variant?: ('primary' | 'secondary') | null;
      newTab?: boolean | null;
    };
    stickyEnabled?: boolean | null;
  };
  footer?: {
    /**
     * Optional footer logo if the footer layout uses a logo.
     */
    logo?: (number | null) | Media;
    logoAlt?: string | null;
    /**
     * Optional footer brand description.
     */
    description?: string | null;
    navigationColumns?:
      | {
          title: string;
          links?:
            | {
                label: string;
                url: string;
                newTab?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    contact?: {
      email?: string | null;
      phone?: string | null;
      address?: string | null;
      ukPhone?: string | null;
      usPhone?: string | null;
      ausPhone?: string | null;
    };
    socialLinks?:
      | {
          platformName: string;
          url: string;
          /**
           * Optional icon key, e.g. linkedin, facebook, instagram.
           */
          iconName?: string | null;
          newTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    cta?: {
      enabled?: boolean | null;
      label?: string | null;
      url?: string | null;
      variant?: ('primary' | 'secondary') | null;
      newTab?: boolean | null;
    };
    copyright?: string | null;
  };
  footerPartners?:
    | {
        image: number | Media;
        label: string;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy fallback. Header navigation uses Header > Header navigation links first.
   */
  primaryNavigation?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy fallback. Footer uses Footer > Footer navigation columns first.
   */
  footerNavigation?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy fallback. Footer copyright uses Footer > Copyright first.
   */
  copyright?: string | null;
  /**
   * Legacy fallback. Footer contact uses Footer > Contact first.
   */
  contact?: {
    officeAddress?: string | null;
    ukPhone?: string | null;
    usPhone?: string | null;
    ausPhone?: string | null;
    email?: string | null;
  };
  /**
   * Legacy/shared social links. Header icons use these if footer social links are empty.
   */
  socialLinks?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Recommended length: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Recommended length: 140-160 characters.
     */
    metaDescription?: string | null;
    keywords?:
      | {
          keyword: string;
          id?: string | null;
        }[]
      | null;
    openGraphImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  logo?: T;
  header?:
    | T
    | {
        logo?: T;
        logoAlt?: T;
        navigation?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              enabled?: T;
              label?: T;
              url?: T;
              variant?: T;
              newTab?: T;
            };
        stickyEnabled?: T;
      };
  footer?:
    | T
    | {
        logo?: T;
        logoAlt?: T;
        description?: T;
        navigationColumns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    newTab?: T;
                    id?: T;
                  };
              id?: T;
            };
        contact?:
          | T
          | {
              email?: T;
              phone?: T;
              address?: T;
              ukPhone?: T;
              usPhone?: T;
              ausPhone?: T;
            };
        socialLinks?:
          | T
          | {
              platformName?: T;
              url?: T;
              iconName?: T;
              newTab?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              enabled?: T;
              label?: T;
              url?: T;
              variant?: T;
              newTab?: T;
            };
        copyright?: T;
      };
  footerPartners?:
    | T
    | {
        image?: T;
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  primaryNavigation?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footerNavigation?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  copyright?: T;
  contact?:
    | T
    | {
        officeAddress?: T;
        ukPhone?: T;
        usPhone?: T;
        ausPhone?: T;
        email?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        openGraphImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'blogs';
          value: number | Blog;
        } | null)
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: number | Testimonial;
        } | null)
      | ({
          relationTo: 'team-members';
          value: number | TeamMember;
        } | null)
      | ({
          relationTo: 'faqs';
          value: number | Faq;
        } | null)
      | ({
          relationTo: 'careers';
          value: number | Career;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}